name: BCV-LR
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.1.0
    - antlr4-python3-runtime==4.9.3
    - beautifulsoup4==4.12.3
    - certifi==2024.6.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - dm-control==1.0.26
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - doy==1.9.2
    - etils==1.11.0
    - filelock==3.14.0
    - fonttools==4.53.0
    - fsspec==2024.5.0
    - funcy==2.0
    - gdown==5.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - glcontext==2.5.0
    - glfw==1.12.0
    - grpcio==1.68.1
    - gym==0.23.1
    - gym-notices==0.0.8
    - gym3==0.3.3
    - idna==3.7
    - imageio==2.34.1
    - imageio-ffmpeg==0.4.8
    - importlib-resources==6.4.5
    - jinja2==3.1.4
    - kiwisolver==1.4.5
    - labmaze==1.0.6
    - lxml==5.3.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.0
    - mdurl==0.1.2
    - moderngl==5.10.0
    - mpmath==1.3.0
    - mujoco==3.2.6
    - networkx==3.3
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - packaging==24.0
    - pillow==10.3.0
    - pip==24.0
    - platformdirs==4.2.2
    - procgen-mirror==0.10.7
    - protobuf==4.25.3
    - psutil==5.9.8
    - pycparser==2.22
    - pygments==2.18.0
    - pyopengl==3.1.7
    - pyparsing==3.1.2
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.1
    - requests==2.32.3
    - rich==13.7.1
    - scipy==1.14.1
    - sentry-sdk==2.3.1
    - setproctitle==1.3.3
    - setuptools==69.5.1
    - six==1.16.0
    - smmap==5.0.1
    - soupsieve==2.5
    - sympy==1.12.1
    - tb-nightly==2.19.0a20241224
    - tensorboard-data-server==0.7.2
    - tensordict==0.4.0
    - termcolor==2.5.0
    - torch==2.3.0
    - torchinfo==1.8.0
    - torchvision==0.18.0
    - tqdm==4.66.4
    - triton==2.3.0
    - typing-extensions==4.12.1
    - urllib3==2.2.1
    - wandb==0.17.0
    - werkzeug==3.1.3
    - wheel==0.43.0
    - zipp==3.21.0
prefix: /home/cyr/anaconda3/envs/BCV-LR

